<?php
/**
 * @file
 */

/**
 * Implements hook_init()
 *
 * Adds the livereload javascript so we don't need the browser extension.
 */
function sb_dev_init() {

  if (!variable_get('sb_dev_use_livereload')) {
    return;
  }

  global $base_url;

  $output = $base_url . '/';
  $output .= drupal_get_path('module', 'sb_dev') . '/livereload.js?';
//  $output .= 'host=' . parse_url($base_url, PHP_URL_HOST);
  $output .= 'host=' . 'localhost';
  $output .= '&port=' . 35777; // Different port than the default livereload.
  $output .= '&snipver=' . 1;
  $output .= '&mindelay' . 1000;
  $output .= '&maxdelay' . 60000;

  drupal_add_js($output, 'external');
}

/**
 * Implements hook_css_alter().
 *
 * Force CSS to be added with link tags, rather than @import. Makes livereload work better.
 */
function sb_dev_css_alter(&$css) {
  foreach ($css as $key => $value) {
    $css[$key]['preprocess'] = FALSE;
  }
}
